language: php
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_script: "make install-dependencies"
script: "make test && cat junit.xml"
